Add seeding to dataset creation, remove label maps
brain-research/realistic-ssl-evaluation pull request #21
Opened 2019-01-31 00:07 UTC by craffel

Resolves #17 and #18. It was impossible to use the existing label maps because the datasets needed to be downloaded, which necessitated creating new label maps. Instead, we should just make the dataset and label map creation processes deterministic by manually setting seeds. This involved changing the README to include label map creation, so I also fixed #18 which specified ImageNet 32x32 creation in the wrong order.

2019-02-07 12:35 UTC, avital commented on README.md
> +We also provide a script to create "label maps", which specify which entries of the dataset should be treated as labeled and unlabeled.
```suggestion
We also provide a script to create "label maps", which specify which entries of the dataset should be treated as labeled and unlabeled. Both of these scripts use an explicitly chosen random seed, so the same dataset order and label maps will be created each time. The random seeds can be overridden, for example to test robustness to different labeled splits.
```

2019-02-07 12:36 UTC, avital commented
Code LGTM. Did you test that both build_tfrecords.py and build_label_maps.py now generate the same results when the seed is fixed?

2019-02-07 12:41 UTC, avital commented
Do you happen to know if Python and numpy guarantee reliability when upgrading to new versions?

2019-02-07 12:42 UTC, avital requested changes
I suggested a small change to the README, and I asked a question about testing reproducibility. Other than that LGTM.

2019-02-07 12:43 UTC, avital commented
Looks like https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.RandomState.html has explicit guarantees which seem stronger than calling into random directly. I don't feel too strongly about this but could be worth switching to that...

2019-02-07 12:46 UTC, avital commented
Specifically, it's possible that a library that we import calls random unknowingly to us, or change when/whether they call random in a version upgrade. Using an explicit RandomState would relieve us of that (tiny) risk of non-determinism when upgrading dependencies.

2019-02-07 18:00 UTC, craffel commented
> Did you test that both build_tfrecords.py and build_label_maps.py now generate the same results when the seed is fixed?

Yes.

> Do you happen to know if Python and numpy guarantee reliability when upgrading to new versions?

Not sure.

> Specifically, it's possible that a library that we import calls random unknowingly to us, or change when/whether they call random in a version upgrade. Using an explicit RandomState would relieve us of that (tiny) risk of non-determinism when upgrading dependencies.

Ok, will make this change.

2019-02-07 18:29 UTC, craffel commented
Ok, pushed a commit to switch to `np.random.RandomState`. The semantics in `build_label_maps.py` changed because of switching from `random.sample` to `np.random.choice`, PTAthoroughL.

2019-02-25 16:53 UTC, avital commented on build_label_map.py
> +                len(label_to_fkeys[label]), n_labeled_per_class, replace=False
Wow, good catch to use `replace=False`.

2019-02-25 16:54 UTC, avital approved these changes

2019-02-25 16:54 UTC, merged